//! Configuration: INI format with case-insensitive keys; the classic key
//! names are kept so configs from earlier versions work unchanged.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Config {
    pub cpu_min: u32,
    pub cpu_max: u32,
    pub ram_target: u32,
    pub check_interval: u32,
    pub service_name: String,
    pub log_file: PathBuf,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            cpu_min: 10,
            cpu_max: 20,
            ram_target: 10,
            check_interval: 5,
            log_file: default_log_path(),
            service_name: "systemhog".to_string(),
        }
    }
}

/// Validated, lowercased systemd unit / service name.
pub fn valid_name(s: &str) -> Result<String, String> {
    let s = s.trim().to_lowercase();
    if s.is_empty() || s.len() > 32 {
        return Err("service name must be 1-32 characters".into());
    }
    if !s.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') {
        return Err("service name may only contain letters, digits, '-' and '_'".into());
    }
    Ok(s)
}

pub fn parse(text: &str) -> Result<Config, String> {
    let mut kv: HashMap<String, String> = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            kv.insert(k.trim().to_uppercase(), v.trim().to_string());
        }
    }
    let num = |key: &str, default: u32| -> Result<u32, String> {
        match kv.get(key) {
            Some(v) => v
                .trim()
                .parse()
                .map_err(|_| format!("{key} has invalid value {v:?}")),
            None => Ok(default),
        }
    };
    let cpu_min = num("TARGET_CPU_MIN", 10)?;
    let cpu_max = num("TARGET_CPU_MAX", 20)?;
    let ram_target = num("TARGET_RAM_USAGE", 10)?;
    let check_interval = num("CHECK_INTERVAL", 5)?;
    if cpu_min >= cpu_max {
        return Err(format!(
            "TARGET_CPU_MIN ({cpu_min}) must be lower than TARGET_CPU_MAX ({cpu_max})"
        ));
    }
    if cpu_max > 100 {
        return Err(format!("TARGET_CPU_MAX must be at most 100, got {cpu_max}"));
    }
    if !(1..=90).contains(&ram_target) {
        return Err(format!("TARGET_RAM_USAGE must be 1..=90, got {ram_target}"));
    }
    if check_interval == 0 {
        return Err("CHECK_INTERVAL must be at least 1 second".into());
    }
    let service_name = match kv.get("SERVICE_NAME") {
        Some(v) => valid_name(v)?,
        None => "systemhog".to_string(),
    };
    let log_file = match kv.get("LOG_FILE") {
        Some(v) if !v.is_empty() => PathBuf::from(v),
        _ => default_log_path(),
    };
    Ok(Config {
        cpu_min,
        cpu_max,
        ram_target,
        check_interval,
        service_name,
        log_file,
    })
}

pub fn to_ini(cfg: &Config) -> String {
    format!(
        "# systemhog configuration (generated by `systemhog init`)\n\
         [CPU_SETTINGS]\n\
         TARGET_CPU_MIN = {}\n\
         TARGET_CPU_MAX = {}\n\n\
         [RAM_SETTINGS]\n\
         TARGET_RAM_USAGE = {}\n\n\
         [SETTINGS]\n\
         CHECK_INTERVAL = {}\n\
         SERVICE_NAME = {}\n\
         LOG_FILE = {}\n",
        cfg.cpu_min,
        cfg.cpu_max,
        cfg.ram_target,
        cfg.check_interval,
        cfg.service_name,
        cfg.log_file.display()
    )
}

pub fn load(path: &Path) -> Result<Config, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("cannot read config {}: {e}", path.display()))?;
    parse(&text).map_err(|e| format!("invalid config {}: {e}", path.display()))
}

pub fn write(path: &Path, cfg: &Config) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    }
    std::fs::write(path, to_ini(cfg)).map_err(|e| format!("cannot write {}: {e}", path.display()))
}

/// One config location per scope: `/etc/systemhog/config.conf` for
/// system-wide (root) installs, `~/.config/systemhog/config.conf` for
/// user installs. The installer and every command follow the invoking
/// user's scope, so a fully user-space setup needs no sudo at all.
pub fn default_config_path() -> PathBuf {
    if crate::sys::is_root() {
        PathBuf::from("/etc/systemhog/config.conf")
    } else {
        base_config_dir().join("systemhog").join("config.conf")
    }
}

/// Platform- and scope-appropriate default log location:
///   Linux, root : /var/log/systemhog.log
///   Linux, user : XDG state dir (~/.local/state/systemhog/systemhog.log)
///   macOS       : ~/Library/Logs/systemhog.log (user-writable, no root needed)
///   Windows     : %LOCALAPPDATA%\systemhog\systemhog.log (per-user app data)
///   other       : XDG state dir
pub fn default_log_path() -> PathBuf {
    #[cfg(target_os = "linux")]
    {
        if crate::sys::is_root() {
            PathBuf::from("/var/log/systemhog.log")
        } else {
            user_state_log()
        }
    }
    #[cfg(target_os = "macos")]
    {
        std::env::var_os("HOME")
            .map(|h| PathBuf::from(h).join("Library/Logs/systemhog.log"))
            .unwrap_or_else(|| PathBuf::from("/var/log/systemhog.log"))
    }
    #[cfg(windows)]
    {
        std::env::var_os("LOCALAPPDATA")
            .map(|d| PathBuf::from(d).join("systemhog").join("systemhog.log"))
            .unwrap_or_else(|| PathBuf::from("systemhog.log"))
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos", windows)))]
    {
        user_state_log()
    }
}

/// XDG state dir default: $XDG_STATE_HOME/systemhog/systemhog.log, or
/// ~/.local/state/systemhog/systemhog.log, or the bare filename.
fn user_state_log() -> PathBuf {
    std::env::var_os("XDG_STATE_HOME")
        .map(|d| PathBuf::from(d).join("systemhog").join("systemhog.log"))
        .or_else(|| {
            std::env::var_os("HOME")
                .map(|h| PathBuf::from(h).join(".local/state/systemhog/systemhog.log"))
        })
        .unwrap_or_else(|| PathBuf::from("systemhog.log"))
}

#[cfg(windows)]
fn base_config_dir() -> PathBuf {
    std::env::var_os("APPDATA")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
}

#[cfg(unix)]
fn base_config_dir() -> PathBuf {
    std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
        .unwrap_or_else(|| PathBuf::from(".config"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_classic_config() {
        let text = "[CPU_SETTINGS]\nTARGET_CPU_MIN = 5\nTARGET_CPU_MAX = 80\n\n\
                    [RAM_SETTINGS]\nTARGET_RAM_USAGE = 16\n\n\
                    [SETTINGS]\nCHECK_INTERVAL = 5\n";
        let c = parse(text).unwrap();
        assert_eq!((c.cpu_min, c.cpu_max, c.ram_target, c.check_interval), (5, 80, 16, 5));
        assert_eq!(c.service_name, "systemhog");
    }

    #[test]
    fn parses_full_config() {
        let c = parse(
            "# comment\n[CPU_SETTINGS]\nTARGET_CPU_MIN = 20\nTARGET_CPU_MAX = 30\n\
             [RAM_SETTINGS]\nTARGET_RAM_USAGE = 40\n\
             [SETTINGS]\nCHECK_INTERVAL = 2\nSERVICE_NAME = MySvc_1\nLOG_FILE = /tmp/x.log\n",
        )
        .unwrap();
        assert_eq!(c.cpu_min, 20);
        assert_eq!(c.cpu_max, 30);
        assert_eq!(c.ram_target, 40);
        assert_eq!(c.check_interval, 2);
        assert_eq!(c.service_name, "mysvc_1");
        assert_eq!(c.log_file, PathBuf::from("/tmp/x.log"));
    }

    #[test]
    fn rejects_invalid_configs() {
        assert!(parse("[CPU_SETTINGS]\nTARGET_CPU_MIN = 80\nTARGET_CPU_MAX = 80\n").is_err());
        assert!(parse("[CPU_SETTINGS]\nTARGET_CPU_MIN = 90\nTARGET_CPU_MAX = 80\n").is_err());
        assert!(parse("[RAM_SETTINGS]\nTARGET_RAM_USAGE = 0\n").is_err());
        assert!(parse("[RAM_SETTINGS]\nTARGET_RAM_USAGE = 91\n").is_err());
        assert!(parse("[SETTINGS]\nCHECK_INTERVAL = 0\n").is_err());
        assert!(parse("[CPU_SETTINGS]\nTARGET_CPU_MIN = abc\n").is_err());
        assert!(parse("[SETTINGS]\nSERVICE_NAME = bad name!\n").is_err());
    }

    #[test]
    fn missing_keys_fall_back_to_defaults() {
        let c = parse("").unwrap();
        assert_eq!(c.cpu_min, 10);
        assert_eq!(c.cpu_max, 20);
        assert_eq!(c.ram_target, 10);
        assert_eq!(c.check_interval, 5);
        assert_eq!(c.service_name, "systemhog");
        assert_eq!(c.log_file, Config::default().log_file);
    }

    #[cfg(unix)]
    #[test]
    fn default_config_matches_scope() {
        if crate::sys::is_root() {
            assert_eq!(default_config_path(), PathBuf::from("/etc/systemhog/config.conf"));
        } else {
            assert!(default_config_path().ends_with("systemhog/config.conf"));
            assert!(!default_config_path().starts_with("/etc"));
        }
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn linux_default_log_matches_scope() {
        if crate::sys::is_root() {
            assert_eq!(Config::default().log_file, PathBuf::from("/var/log/systemhog.log"));
        } else {
            assert!(Config::default().log_file.ends_with("systemhog/systemhog.log"));
        }
    }

    #[test]
    fn ini_roundtrip() {
        let mut cfg = Config::default();
        cfg.cpu_min = 7;
        cfg.cpu_max = 42;
        cfg.ram_target = 23;
        cfg.check_interval = 9;
        cfg.service_name = "mysvc".into();
        cfg.log_file = PathBuf::from("/var/log/mysvc.log");
        let parsed = parse(&to_ini(&cfg)).unwrap();
        assert_eq!(parsed, cfg);
    }

    #[test]
    fn names_are_validated() {
        assert_eq!(valid_name("MySvc"), Ok("mysvc".into()));
        assert!(valid_name("").is_err());
        assert!(valid_name("a b").is_err());
        assert!(valid_name("a/b").is_err());
        assert!(valid_name(&"x".repeat(33)).is_err());
    }
}
